networks:
  wpsite:
volumes:
  dbvol:
services:
 db:
  image: mysql:5.6
  networks:
    - wpsite
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: wordpress
    MYSQL_USER: navyanu
    MYSQL_PASSWORD: wordpress
  volumes:
    - dbvol:/var/lib/mysql
 myweb:
  depends_on:
    - db
  image: wordpress
  ports:
    - 8282:80
  networks:
    - wpsite
  environment:
    WORDPRESS_DB_HOST: db:3306
    WORDPRESS_DB_NAME: wordpress
    WORDPRESS_DB_USER: navyanu
    WORDPRESS_DB_PASSWORD: wordpress





